image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:docker

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE
    - docker run --rm --privileged 
                 -e DEB_REPO="${KERNE_DEB_REPO}"
                 -e DEB_REPO_PUBLIC_KEY="${DEP_REPO_PUBLIC_KEY}"
                 -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
                 -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
                 -e AWS_REGION="${AWS_REGION}"
                 -e AWS_BUCKET="${AWS_BUCKET}"
                 -e CI_JOB_ID="${CI_JOB_ID}" 
                 -e CI_PIPELINE_ID="${CI_PIPELINE_ID}" 
                 -v $PWD:/work -w /work 
                 $CONTAINER_IMAGE /bin/bash -c /work/build.sh
